# Copyright (c) 2014 Docker, Inc.

version: '3.1'

services:

  redmine:
    build:
      context: ./redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
    volumes:
      - ./redmine/data/files:/usr/src/redmine/files
      - ./redmine/data/plugins:/usr/src/redmine/plugins
      - ./redmine/data/log:/usr/src/redmine/log
    depends_on:
      - db

  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    volumes:
      - ./mariadb/data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
